"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { PageHeader } from "@/components/shared/page-header";
import { ProductSelector } from "@/components/shared/product-selector";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useProducts } from "@/hooks/use-catalog";
import { useWarehouses } from "@/hooks/use-organization";
import { useDirectDispatch } from "@/hooks/use-stock-transfer";
import { stockBatchesApi, stockInventoriesApi, stockTransfersApi } from "@/lib/api";
import { useAuthStore } from "@/store/auth-store";
import type { StockBatch } from "@/types";

type Line = { itemCode: string; batchId: string; quantity: string; remarks: string; batches: StockBatch[]; loading: boolean };
const blank = (): Line => ({ itemCode: "", batchId: "", quantity: "", remarks: "", batches: [], loading: false });
export default function DirectTransferPage() {
  const sourceCode = useAuthStore((state) => state.user?.warehouseCode) ?? ""; const warehouses = useWarehouses(); const products = useProducts({ isActive: true }); const mutation = useDirectDispatch(); const [destination, setDestination] = useState(""); const [vehicleNo, setVehicleNo] = useState(""); const [driverName, setDriverName] = useState(""); const [remarks, setRemarks] = useState(""); const [lines, setLines] = useState<Line[]>([blank()]); const [confirm, setConfirm] = useState(false);
  if (!sourceCode) return <AssignmentError />;
  const destinations = (warehouses.data ?? []).filter((warehouse) => warehouse.isActive && !warehouse.isCentralWarehouse && (!warehouse.parentWarehouseCode || warehouse.parentWarehouseCode === sourceCode));
  const selectItem = async (index: number, itemCode: string) => { setLines((all) => all.map((line, i) => i === index ? { ...line, itemCode, batchId: "", batches: [], loading: true } : line)); try { const stocks = await stockInventoriesApi.list({ itemCode, warehouseCode: sourceCode }); const batches = (await Promise.all(stocks.map((stock) => stockBatchesApi.listByStock(stock.stockId)))).flat().filter((batch) => batch.status === "Available" && batch.availableQty > 0); setLines((all) => all.map((line, i) => i === index ? { ...line, batches, loading: false } : line)); } catch { setLines((all) => all.map((line, i) => i === index ? { ...line, loading: false } : line)); toast.error("Available Central Warehouse batches could not be loaded."); } };
  const review = () => { if (!destination || !vehicleNo.trim() || !driverName.trim()) { toast.error("Destination warehouse, vehicle number and driver name are required."); return; } if (lines.some((line) => !line.itemCode || !line.batchId || Number(line.quantity) <= 0)) { toast.error("Select an item, available batch and positive quantity for every line."); return; } const exceeds = lines.some((line) => { const available = line.batches.find((batch) => String(batch.batchId) === line.batchId)?.availableQty ?? 0; const allocated = lines.filter((item) => item.batchId === line.batchId).reduce((sum, item) => sum + Number(item.quantity), 0); return allocated > available; }); if (exceeds) { toast.error("A batch allocation exceeds its available Central Warehouse quantity."); return; } setConfirm(true); };
  const dispatch = () => mutation.mutate({ destinationWarehouseCode: destination, vehicleNo: vehicleNo.trim(), driverName: driverName.trim(), remarks: remarks.trim() || null, lines: lines.map((line) => ({ itemCode: line.itemCode, batchId: Number(line.batchId), quantity: Number(line.quantity), remarks: line.remarks.trim() || null })) }, { onSuccess: (response) => { setConfirm(false); const dispatchResult = response.data; toast.success("Direct transfer dispatched.", { description: `${dispatchResult.dispatchNo} is ready to print.` }); void stockTransfersApi.deliveryNote(dispatchResult.dispatchId, dispatchResult.dispatchNo); setDestination(""); setVehicleNo(""); setDriverName(""); setRemarks(""); setLines([blank()]); } });
  return <div className="space-y-6"><PageHeader title="Direct Transfer" description={`Dispatch assigned Central Warehouse ${sourceCode} stock directly to a branch warehouse without a branch request.`} />
    <div className="space-y-5 rounded-xl border bg-card p-6"><div className="grid gap-4 sm:grid-cols-3"><Field label="Destination Branch Warehouse *"><Select value={destination} onValueChange={setDestination}><SelectTrigger><SelectValue placeholder={warehouses.isLoading ? "Loading..." : "Select destination"} /></SelectTrigger><SelectContent>{destinations.map((warehouse) => <SelectItem key={warehouse.warehouseCode} value={warehouse.warehouseCode}>{warehouse.warehouseName} ({warehouse.warehouseCode})</SelectItem>)}</SelectContent></Select></Field><Field label="Vehicle No. *"><Input value={vehicleNo} onChange={(e) => setVehicleNo(e.target.value)} /></Field><Field label="Driver Name *"><Input value={driverName} onChange={(e) => setDriverName(e.target.value)} /></Field></div>
    <div className="space-y-3">{lines.map((line, index) => <div key={index} className="grid gap-2 rounded-lg border p-3 lg:grid-cols-[1.4fr_1fr_120px_1fr_auto]"><ProductSelector products={products.data ?? []} value={line.itemCode} onChange={(value) => void selectItem(index, value)} isLoading={products.isLoading} /><Select value={line.batchId} onValueChange={(value) => setLines((all) => all.map((item, i) => i === index ? { ...item, batchId: value } : item))} disabled={!line.itemCode || line.loading}><SelectTrigger><SelectValue placeholder={line.loading ? "Loading batches..." : "Select batch"} /></SelectTrigger><SelectContent>{line.batches.map((batch) => <SelectItem key={batch.batchId} value={String(batch.batchId)}>{batch.batchNo} · {batch.availableQty} available</SelectItem>)}</SelectContent></Select><Input type="number" min="0.01" step="0.01" placeholder="Qty" value={line.quantity} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, quantity: e.target.value } : item))} /><Input placeholder="Line remarks" value={line.remarks} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, remarks: e.target.value } : item))} /><Button variant="ghost" size="icon" disabled={lines.length === 1} onClick={() => setLines((all) => all.filter((_, i) => i !== index))}><Trash2 /></Button></div>)}</div><Button variant="outline" onClick={() => setLines((all) => [...all, blank()])}><Plus /> Add Item</Button><Field label="Dispatch Remarks"><Textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} /></Field><div className="flex justify-end"><Button onClick={review} disabled={mutation.isPending}>{mutation.isPending ? "Dispatching..." : "Review Direct Dispatch"}</Button></div></div>
    <ConfirmDialog open={confirm} onOpenChange={setConfirm} title="Dispatch Central Warehouse stock?" description="Central stock will decrease immediately. Destination branch stock will increase only after branch receipt." confirmLabel="Confirm Dispatch" loading={mutation.isPending} onConfirm={dispatch} />
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function AssignmentError() { return <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-6"><h1 className="font-semibold text-destructive">Main Warehouse is not assigned.</h1><p className="text-sm text-muted-foreground">Contact Admin.</p></div>; }
