"use client";
import { useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { PageHeader } from "@/components/shared/page-header";
import { ProductSelector } from "@/components/shared/product-selector";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useProducts } from "@/hooks/use-catalog";
import { useCreateOpeningStock } from "@/hooks/use-stock";
import { useAuthStore } from "@/store/auth-store";
import { formatMoney } from "@/lib/format";
import type { OpeningStockResult } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
export default function CentralStockInPage() {
  const code = useAuthStore((state) => state.user?.warehouseCode) ?? ""; const products = useProducts({ isActive: true }); const mutation = useCreateOpeningStock(); const [result, setResult] = useState<OpeningStockResult | null>(null);
  const form = useForm({ defaultValues: { itemCode: "", quantity: "", unitCost: "", sellingPrice: "", expiryDate: "", openingDate: today(), referenceNo: "", remarks: "" } }); const itemCode = useWatch({ control: form.control, name: "itemCode" });
  if (!code) return <AssignmentError />;
  const submit = form.handleSubmit((v) => mutation.mutate({ itemCode: v.itemCode, branchCode: null, warehouseCode: code, quantity: Number(v.quantity), unitCost: Number(v.unitCost), sellingPrice: Number(v.sellingPrice), expiryDate: v.expiryDate || null, openingDate: v.openingDate, referenceNo: v.referenceNo.trim() || null, remarks: v.remarks.trim() || null }, { onSuccess: (response) => { setResult(response.data); form.reset({ itemCode: "", quantity: "", unitCost: "", sellingPrice: "", expiryDate: "", openingDate: today(), referenceNo: "", remarks: "" }); } }));
  return <div className="space-y-6"><PageHeader title="Central Stock In" description={`Receive opening stock into assigned Main Warehouse ${code}. Batch number is generated by the backend.`} />
    <form onSubmit={submit} className="max-w-4xl space-y-5 rounded-xl border bg-card p-6"><div className="space-y-1.5"><Label>Product *</Label><ProductSelector products={products.data ?? []} value={itemCode} onChange={(value) => { form.setValue("itemCode", value, { shouldValidate: true }); const date = form.getValues("openingDate").replaceAll("-", ""); form.setValue("referenceNo", `CENTRAL-${value}-${date}`); }} isLoading={products.isLoading} /><input type="hidden" {...form.register("itemCode", { required: true })} /></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Quantity *"><Input type="number" min="0.01" step="0.01" {...form.register("quantity", { required: true, validate: (v) => Number(v) > 0 })} /></Field><Field label="Unit Cost *"><Input type="number" min="0" step="0.01" {...form.register("unitCost", { required: true, validate: (v) => Number(v) >= 0 })} /></Field><Field label="Selling Price *"><Input type="number" min="0" step="0.01" {...form.register("sellingPrice", { required: true, validate: (v) => Number(v) >= 0 })} /></Field><Field label="Expiry Date"><Input type="date" {...form.register("expiryDate")} /></Field><Field label="Opening Date *"><Input type="date" {...form.register("openingDate", { required: true })} /></Field><Field label="Reference Number"><Input {...form.register("referenceNo")} /></Field></div><Field label="Remarks"><Textarea {...form.register("remarks")} /></Field><div className="flex justify-end"><Button disabled={mutation.isPending}>{mutation.isPending ? "Receiving stock..." : "Receive Central Stock"}</Button></div></form>
    {result && <div className="max-w-4xl rounded-xl border border-success/30 bg-success/5 p-4"><p className="font-semibold text-success">Central stock received successfully.</p><p className="mt-1 text-sm">Batch {result.batchNo} · Quantity {result.quantity} · Total {formatMoney(result.totalValue)} · Reference {result.referenceNo || "—"}</p></div>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function AssignmentError() { return <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-6"><h1 className="font-semibold text-destructive">Main Warehouse is not assigned.</h1><p className="text-sm text-muted-foreground">Contact Admin.</p></div>; }
